 

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.12.x'

      - name: Install dependencies
        run: npm install --force

      - name: Build
        run: npm run build  

      - name: Deploy to GitHub Pages
        uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/my-portfolio
          publish_branch: gh-pages
